#pragma once

enum class AsyncMqttClientDisconnectReason : int16_t {
  TCP_DISCONNECTED = 0,

  MQTT_UNACCEPTABLE_PROTOCOL_VERSION = 1,
  MQTT_IDENTIFIER_REJECTED = 2,
  MQTT_SERVER_UNAVAILABLE = 3,
  MQTT_MALFORMED_CREDENTIALS = 4,
  MQTT_NOT_AUTHORIZED = 5,

  ESP8266_NOT_ENOUGH_SPACE = 6,

  TLS_BAD_FINGERPRINT = 7,
  //NotAuthorized = 135

};
